export const testUrl = 'http://localhost:4000';
export const bunIngredientCategory = '[data-cy=buns-category]';
export const mainIngredientCategory = '[data-cy=mains-category]';
export const sauceIngredientCategory = '[data-cy=sauces-category]';
export const mainIngredient = '[data-cy=main-ingredient]';
export const modal = '[data-cy=modal]';
export const ingredientCard = '[data-cy=ingredient-card]';
export const modalCloseBtn = '[data-cy=modal-close-btn]';
export const constructor = '[data-cy=constructor]';
